/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package final_project;

import java.util.ArrayList;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Peter Standing - UP817277
 */
public class homePage extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public homePage(String stuName, String stuSchool) {
        initComponents();
        currName = stuName;
        currSchool = stuSchool;
        this.setExtendedState(homePage.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String diff,operation,currName,currSchool;
    int numQ;
    ImageIcon icon;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        ks1Label = new javax.swing.JLabel();
        ks2Label = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        profileLabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ks1Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JButton ks1GameButton = new javax.swing.JButton();
        easyDiff = new javax.swing.JToggleButton();
        mediumDiff = new javax.swing.JToggleButton();
        hardDiff = new javax.swing.JToggleButton();
        opChooser = new javax.swing.JComboBox<>();
        ks1RevisionButton = new javax.swing.JButton();
        ks2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rev2Button = new javax.swing.JButton();
        KS2Game = new javax.swing.JButton();
        easyKS2 = new javax.swing.JToggleButton();
        mediumKS2 = new javax.swing.JToggleButton();
        hardKS2 = new javax.swing.JToggleButton();
        skillChooser = new javax.swing.JComboBox<>();
        profilePanel = new javax.swing.JPanel();
        profileTitle = new javax.swing.JLabel();
        rocketScore = new javax.swing.JLabel();
        nameProfile = new javax.swing.JLabel();
        highRocket = new javax.swing.JLabel();
        schoolLabel = new javax.swing.JLabel();
        profAvatar = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        highSum = new javax.swing.JLabel();
        schoolProfile = new javax.swing.JLabel();
        sumScore = new javax.swing.JLabel();
        avaChoice = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math App Home");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        homeLabel.setBackground(new java.awt.Color(153, 255, 255));
        homeLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        homeLabel.setText("Home Page");
        homeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });

        ks1Label.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ks1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ks1Label.setText("KS1");
        ks1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ks1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ks1LabelMouseClicked(evt);
            }
        });

        ks2Label.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ks2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ks2Label.setText("KS2");
        ks2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ks2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ks2LabelMouseClicked(evt);
            }
        });

        logLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        logLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logLabel.setText("Log Out");
        logLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logLabelMouseClicked(evt);
            }
        });

        profileLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setText("Profile");
        profileLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(profileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ks2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ks1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(ks1Label)
                .addGap(18, 18, 18)
                .addComponent(ks2Label)
                .addGap(18, 18, 18)
                .addComponent(profileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logLabel)
                .addContainerGap())
        );

        jLayeredPane2.setBackground(new java.awt.Color(255, 0, 204));
        jLayeredPane2.setLayout(new javax.swing.OverlayLayout(jLayeredPane2));

        homePanel.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome To The App");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
        );

        jLayeredPane2.add(homePanel);

        ks1Panel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("KS1 Panel");

        ks1GameButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ks1GameButton.setText("Game");
        ks1GameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ks1GameButtonActionPerformed(evt);
            }
        });

        easyDiff.setText("Easy");
        easyDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyDiffActionPerformed(evt);
            }
        });

        mediumDiff.setText("Medium");
        mediumDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumDiffActionPerformed(evt);
            }
        });

        hardDiff.setText("Hard");
        hardDiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardDiffActionPerformed(evt);
            }
        });

        opChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Addition", "Subtraction", "Multiply", "Divide" }));

        ks1RevisionButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ks1RevisionButton.setText("Revision");
        ks1RevisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ks1RevisionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ks1PanelLayout = new javax.swing.GroupLayout(ks1Panel);
        ks1Panel.setLayout(ks1PanelLayout);
        ks1PanelLayout.setHorizontalGroup(
            ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ks1PanelLayout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ks1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ks1RevisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ks1PanelLayout.createSequentialGroup()
                        .addComponent(ks1GameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ks1PanelLayout.createSequentialGroup()
                        .addComponent(opChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mediumDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hardDiff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(easyDiff, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(261, 261, 261))))
        );
        ks1PanelLayout.setVerticalGroup(
            ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ks1PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addComponent(easyDiff)
                .addGap(18, 18, 18)
                .addGroup(ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumDiff)
                    .addComponent(opChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hardDiff)
                .addGap(18, 18, 18)
                .addGroup(ks1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ks1GameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ks1RevisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(ks1Panel);

        ks2Panel.setBackground(new java.awt.Color(102, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("KS2 Panel");

        rev2Button.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rev2Button.setText("Revision");
        rev2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rev2ButtonActionPerformed(evt);
            }
        });

        KS2Game.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        KS2Game.setText("Game");
        KS2Game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KS2GameActionPerformed(evt);
            }
        });

        easyKS2.setText("Easy");
        easyKS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyKS2ActionPerformed(evt);
            }
        });

        mediumKS2.setText("Medium");
        mediumKS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumKS2ActionPerformed(evt);
            }
        });

        hardKS2.setText("Hard");
        hardKS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardKS2ActionPerformed(evt);
            }
        });

        skillChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Addition", "Subtraction", "Multiplication", "Division", "Rounding", "Algebra", "Percentages", "Ratio", "Fraction" }));

        javax.swing.GroupLayout ks2PanelLayout = new javax.swing.GroupLayout(ks2Panel);
        ks2Panel.setLayout(ks2PanelLayout);
        ks2PanelLayout.setHorizontalGroup(
            ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ks2PanelLayout.createSequentialGroup()
                .addGroup(ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ks2PanelLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(rev2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KS2Game, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ks2PanelLayout.createSequentialGroup()
                        .addGroup(ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ks2PanelLayout.createSequentialGroup()
                                .addGap(598, 598, 598)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ks2PanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(skillChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hardKS2)
                            .addComponent(mediumKS2)
                            .addComponent(easyKS2))))
                .addGap(277, 277, 277))
        );
        ks2PanelLayout.setVerticalGroup(
            ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ks2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(easyKS2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumKS2)
                    .addComponent(skillChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardKS2)
                .addGap(38, 38, 38)
                .addGroup(ks2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rev2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KS2Game, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249))
        );

        jLayeredPane2.add(ks2Panel);

        profilePanel.setBackground(new java.awt.Color(255, 255, 153));

        profileTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        profileTitle.setText("User Profile");

        rocketScore.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        rocketScore.setText("rocket score");

        nameProfile.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nameProfile.setText("name");

        highRocket.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        highRocket.setText("High Score Rocket:");

        schoolLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        schoolLabel.setText("School:");

        nameLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nameLabel.setText("Name:");

        highSum.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        highSum.setText("High Score Sum Snap:");

        schoolProfile.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        schoolProfile.setText("school");

        sumScore.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        sumScore.setText("sum score");

        avaChoice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        avaChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Flowers", "Sun", "Star", "Pencil" }));

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(nameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(profAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(profileTitle)
                                    .addComponent(highRocket, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(rocketScore, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                                .addComponent(highSum)
                                .addGap(18, 18, 18)
                                .addComponent(sumScore, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                                .addComponent(schoolLabel)
                                .addGap(18, 18, 18)
                                .addComponent(schoolProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(avaChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(changeButton)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(profileTitle)
                        .addGap(103, 103, 103)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(schoolLabel)
                            .addComponent(schoolProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(highSum)
                            .addComponent(sumScore)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(profAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(highRocket)
                    .addComponent(rocketScore))
                .addGap(37, 37, 37)
                .addComponent(avaChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jLayeredPane2.add(profilePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ks2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ks2LabelMouseClicked
        //Opens the KS2 Panel
        ks2Panel.show();
        ks1Panel.hide();
        homePanel.hide();
        profilePanel.hide();
    }//GEN-LAST:event_ks2LabelMouseClicked

    private void ks1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ks1LabelMouseClicked
        //Opens the KS1 Panel
        ks1Panel.show();
        ks2Panel.hide();
        homePanel.hide();
        profilePanel.hide();
    }//GEN-LAST:event_ks1LabelMouseClicked

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        //Opens the Home Panel
        homePanel.show();
        ks1Panel.hide();
        ks2Panel.hide();
        profilePanel.hide();
    }//GEN-LAST:event_homeLabelMouseClicked

    private void logLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logLabelMouseClicked
        //Logs out the users Account ready for the next user
        this.dispose();
        login.main();
    }//GEN-LAST:event_logLabelMouseClicked

    private void profileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileLabelMouseClicked
        //Opens the Users Profile
        profilePanel.show();
        homePanel.hide();
        ks1Panel.hide();
        ks2Panel.hide();
        
        nameProfile.setText(currName);
        rocketScore.setText(currSchool);
        
        ArrayList <String> nameList = keyFunctions.readFile("db/names.txt");
        ArrayList <String> profPic = keyFunctions.readFile("db/profile.txt"); 
        
        int k = nameList.indexOf(currName);
        String currPic = profPic.get(k);
        if (currPic.equals("car")){
           icon = new ImageIcon("avatars/car.png"); 
        } else if (currPic.equals("flowers")){
           icon = new ImageIcon("avatars/flowers.png"); 
        } else if (currPic.equals("sun")){
           icon = new ImageIcon("avatars/sun.png"); 
        } else if (currPic.equals("star")){
           icon = new ImageIcon("avatars/star.png"); 
        } else if (currPic.equals("pencil")){
           icon = new ImageIcon("avatars/pencil.png");
        }
        profAvatar.setIcon(icon);
               
    }//GEN-LAST:event_profileLabelMouseClicked

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        ArrayList <String> nameList = keyFunctions.readFile("db/names.txt");
        ArrayList <String> profPic = keyFunctions.readFile("db/profile.txt"); 
        
        int k = nameList.indexOf(currName);
        
        String av = (String)avaChoice.getSelectedItem();
        if (av.equals("Car")){
            System.out.print("test");
            keyFunctions.writeFile("db/profile.txt","car",k);
        }
        if (av.equals("Flowers")){
            keyFunctions.writeFile("db/profile.txt","flowers",k);
        }
        if (av.equals("Sun")){
            keyFunctions.writeFile("db/profile.txt","sun",k);
        }
        if (av.equals("Star")){
            keyFunctions.writeFile("db/profile.txt","star",k);
        }
        if (av.equals("Pencil")){
            keyFunctions.writeFile("db/profile.txt","pencil",k);
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void hardDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardDiffActionPerformed
        mediumDiff.setSelected(false);
        easyDiff.setSelected(false);
    }//GEN-LAST:event_hardDiffActionPerformed

    private void mediumDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumDiffActionPerformed
        easyDiff.setSelected(false);
        hardDiff.setSelected(false);
    }//GEN-LAST:event_mediumDiffActionPerformed

    private void easyDiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyDiffActionPerformed
        mediumDiff.setSelected(false);
        hardDiff.setSelected(false);
    }//GEN-LAST:event_easyDiffActionPerformed

    private void ks1GameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ks1GameButtonActionPerformed
        if (easyDiff.isSelected()){
            diff = "easy";
            numQ = 12;
        }
        if (mediumDiff.isSelected()){
            diff = "medium";
            numQ = 16;
        }
        if (hardDiff.isSelected()){
            diff = "hard";
            numQ = 20;
        }

        String opSelected = (String)opChooser.getSelectedItem();

        if (opSelected.equals("Addition")){
            operation = "+";
        }
        if (opSelected.equals("Subtraction")){
            operation = "-";
        }
        if (opSelected.equals("Multiply")){
            operation = "*";
        }
        if (opSelected.equals("Divide")){
            operation = "/";
        }

        //Generates the Canavs on a JFrame
        gameOne.main(operation,numQ,diff);
    }//GEN-LAST:event_ks1GameButtonActionPerformed

    private void ks1RevisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ks1RevisionButtonActionPerformed
        ks1Revision.main();
    }//GEN-LAST:event_ks1RevisionButtonActionPerformed

    private void rev2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rev2ButtonActionPerformed
        ks2Revision.main();
    }//GEN-LAST:event_rev2ButtonActionPerformed

    private void KS2GameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KS2GameActionPerformed
        if (easyKS2.isSelected()){
            diff = "easy";
        }
        if (mediumKS2.isSelected()){
            diff = "medium";
        }
        if (hardKS2.isSelected()){
            diff = "hard";
        }
        
        String skillSelected = (String)skillChooser.getSelectedItem();

        //Generates the Canavs on a JFrame
        gameTwo.main(diff,skillSelected);
    }//GEN-LAST:event_KS2GameActionPerformed

    private void easyKS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyKS2ActionPerformed
        mediumKS2.setSelected(false);
        hardKS2.setSelected(false);
    }//GEN-LAST:event_easyKS2ActionPerformed

    private void mediumKS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumKS2ActionPerformed
        easyKS2.setSelected(false);
        hardKS2.setSelected(false);
    }//GEN-LAST:event_mediumKS2ActionPerformed

    private void hardKS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardKS2ActionPerformed
        mediumKS2.setSelected(false);
        easyKS2.setSelected(false);
    }//GEN-LAST:event_hardKS2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String name, String school) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage(name,school).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KS2Game;
    private javax.swing.JComboBox<String> avaChoice;
    private javax.swing.JButton changeButton;
    private javax.swing.JToggleButton easyDiff;
    private javax.swing.JToggleButton easyKS2;
    private javax.swing.JToggleButton hardDiff;
    private javax.swing.JToggleButton hardKS2;
    private javax.swing.JLabel highRocket;
    private javax.swing.JLabel highSum;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ks1Label;
    private javax.swing.JPanel ks1Panel;
    private javax.swing.JButton ks1RevisionButton;
    private javax.swing.JLabel ks2Label;
    private javax.swing.JPanel ks2Panel;
    private javax.swing.JLabel logLabel;
    private javax.swing.JToggleButton mediumDiff;
    private javax.swing.JToggleButton mediumKS2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameProfile;
    private javax.swing.JComboBox<String> opChooser;
    private javax.swing.JLabel profAvatar;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profileTitle;
    private javax.swing.JButton rev2Button;
    private javax.swing.JLabel rocketScore;
    private javax.swing.JLabel schoolLabel;
    private javax.swing.JLabel schoolProfile;
    private javax.swing.JComboBox<String> skillChooser;
    private javax.swing.JLabel sumScore;
    // End of variables declaration//GEN-END:variables
}
